### DISCUSSION TITLE
How to use custom objection models in codeproject.ai

### DISCUSSION THREAD

**Discussion by Aadi4401** [codeproject/CodeProject.AI-Server#278] [Q&A]
Hello everyone,

I have some custom-trained YOLOv8 models for PPE detection and weapon detection. I have the .pt files for these models.

Can I use these models in CodeProject.AI? If yes, could someone guide me through the steps to set them up?

Thanks in advance!

@miguelangel-nubla @ChrisMaunder @seth-planet @mailseth

**Comment by hinachow1** [comment]
How cool! I hope someone answers your query!

**Comment by ivan0636** [comment]
hello 
you get a workaround for this?

**Comment by john-** [comment]
I am using CodeProject.AI on docker and have it mostly working with a custom YOLO v8 model.

My docker-compose.yaml (note the references to `codeproject_ai_custom_models`;
```
services:
  CodeProjectAI:
    image: codeproject/ai-server
    container_name: codeproject-ai-server-cpu
    hostname: codeproject-ai-server
    restart: unless-stopped
    ports:
      - "32168:32168"
    environment:
      - TZ=America/Chicago
      # - Modules:ObjectDetectionYOLOv5-6.2:MODEL_SIZE=Large   cannot get this to work.  I wound up setting this in the UI (gear icon for the detector).
    volumes:
      - codeproject_ai_data:/etc/codeproject/ai
      - codeproject_ai_modules:/app/modules
      - type: bind
        source: codeproject_ai_custom_models
        target: /app/modules/ObjectDetectionYOLOv8/custom-models

volumes:
  codeproject_ai_data:
  codeproject_ai_modules:
  codeproject_ai_custom_models:
```

I placed my my model in that directory and restarted CodePoroject.AI.

The only think I am not happy with is that on startup I need to go into CodeProject.AI Explorer and do a detection with that custom model.   Note:  This method might remove ability to use built-in models.  I do not recall.

It has been a while since I did this so hopefully didn't miss any steps.

![image](https://github.com/user-attachments/assets/2799ac8f-f548-4e41-9048-8c3551f1b655)
