### DISCUSSION TITLE
Custom YOLOv8 Model

### DISCUSSION THREAD

**Discussion by john-** [codeproject/CodeProject.AI-Server#288] [Show and tell]
Thanks for all the great work on this software.

I was able to get Codeproject.AI-Server with by custom YOLOv8 model.  I ran across [this document](https://codeproject.github.io/codeproject.ai/install/running_in_docker.html#common-example-specifying-a-folder-for-custom-object-detection-files-for-the-objectdetectionyolo-module)  which got me the insights I needed.

I modified it for docker compose:
```
[snip]
    volumes:
      - codeproject_ai_data:/etc/codeproject/ai
      - codeproject_ai_modules:/app/modules
      - type: bind
        source: codeproject_ai_custom_models
        target: /app/modules/ObjectDetectionYOLOv8/custom-models
volumes:
  codeproject_ai_data:
  codeproject_ai_modules:
  codeproject_ai_custom_models:
```

*Note*: The docs reference a generic `ObjectDetectionYolo` directory in the bind mount directive.  After installing the YOLOv8 module it appeared as `ObjectDetectionYOLOv8`.

It seems like I needed to have the codeproject_ai_custom_models as a bind mount for the container to see the contents on the host.  I placed my model in that directory and after a restart was able to see (and use) the model in Codeproject.AI Explorer.

I see there is work on YOLOv11 in progress and hopefully we can do the same custom model with that as we can with v8!
