### ISSUE TITLE
Face recognition with CUDA stopped working v1.6.6.0

### ISSUE THREAD

**Issue by elad-bar** [codeproject/CodeProject.AI-Server#24]
**Area of Concern**
- Server
- Behaviour of one or more Modules- Face recongition

Upgrading to 1.6.6.0 caused face recognition with CUDA stopped working, 
configuration was updated but it presented that the module loaded without CUDA and didn't accept new requests.

Reverted  to 1.6.5.0 and it's working.

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 1.6.6.0
 - OS: Docker over Ubuntu Server 22.04
 - System RAM 96GB
 - GPU GeForce RTX 2060
 - GPU RAM 6Gb

**Comment by elad-bar** [comment]
no errors, just not processing, in the web page it presented all the modules, the face reco module enabled on cpu, trying to change it to gpu doing nothing

**Comment by matthewDDennis** [comment]
I have found why the GPU wasn't enabled.  It had been disabled in the modulesettings.docker.json file and another bug prevented it from being enabled.
I fix this for the next release.

You say it is not responding to new requests.
What is making the requests?
What is the command you are using to start the docker image?

**Comment by elad-bar** [comment]
I'm using it since v1.5.6.2,
I'm using Shinobi Video NVR, I wrote the plugin of it connects to DeepStack,
After switching to your solution there were almost no adjustements as the request / response and endpoints are the same (except one property was available in DeepStack and not available here).

docker compose:
```yaml
version: "3.9"

services:
  codeproject-ai-server:
    image: codeproject/ai-server:gpu
    container_name: codeproject-ai-server
    hostname: codeproject-ai-server
    restart: unless-stopped
    runtime: nvidia
    command:
      - --Modules:BackgroundRemover:Activate=False
      - --Modules:BackgroundRemoval:Activate=False
      - --Modules:CustomDetection:Activate=False
      - --Modules:CustomObjectDetection:Activate=False
      - --Modules:PortraitFilter:Activate=False
      - --Modules:SceneClassification:Activate=False
      - --Modules:SceneClassification:EnvironmentVariables:VISION-SCENE=False
      - --Modules:VisionObjectDetection:Activate=False
      - --Modules:VisionObjectDetection:EnvironmentVariables:VISION-DETECTION=False
      - --Modules:FaceProcessing:Activate=True
      - --Modules:FaceProcessing:EnvironmentVariables:VISION-FACE=True
      - --Modules:FaceProcessing:EnvironmentVariables:MODE=High
      - --Modules:FaceProcessing:EnvironmentVariables:USE_CUDA=True
    env_file:
      - ../env/common.env
      - ../env/codeproject-ai-server.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/bar/docker/codeproject-ai-server/data:/usr/share/CodeProject/AI
    ports:
      - 5000:5000
```

environment variables:
```bash
CPAI_ERRLOG_APIKEY=
```

request is simple nodejs request to the server according to the guideline, nothing change over there
